"""
Seed data for the seed_products management command. Image filenames
below reference files expected in seed_images/ just as they were
downloaded and name.  Categories and products
get added incrementally. """

CATEGORIES = [
    {"name": "Ankara Fabrics", "description": "Authentic wax print and lace fabric bundles, sold by the yard."},
    {"name": "Spices & Sauce Kits", "description": "Pre-measured spice blends for authentic West African cooking."},
    {"name": "Homeware", "description": "Kitchen, dining, and bedding pieces for the home."},
    {"name": "Beads & Jewellery", "description": "Handmade beaded and traditional jewellery for men and women."},
    {"name": "Accessories", "description": "Bags and footwear with West African design influence."},
    {"name": "Traditional Wear", "description": "Ready-to-wear traditional and cultural clothing."},
]

PRODUCTS = [
    {
        "name": "Jollof Rice Spice Kit",
        "category": "Spices & Sauce Kits",
        "description": "A pre-measured blend of smoked paprika, thyme, curry powder, and dried chili built specifically for party-style jollof rice. Just add tomatoes, pepper, and rice for the real thing without hunting down eight separate jars.",
        "price": 11.50,
        "stock_quantity": 30,
        "is_featured": True,
        "images": ["spices-sauces-kit-01-a.jpg", "spices-sauces-kit-01-b.jpg"],
    },
    {
        "name": "Suya Spice Blend (Yaji)",
        "category": "Spices & Sauce Kits",
        "description": "A ground peanut and pepper suya spice mix, the same blend used by roadside suya sellers across Nigeria. Rub it onto grilled beef, chicken, or even vegetables for a smoky, peppery crust.",
        "price": 9.99,
        "stock_quantity": 25,
        "is_featured": True,
        "images": ["spices-sauces-kit-02-a.jpg", "spices-sauces-kit-02-b.jpg"],
    },
    {
        "name": "Egusi Soup Spice Mix",
        "category": "Spices & Sauce Kits",
        "description": "The seasoning base for a proper pot of egusi soup, ground crayfish, stock cubes, and pepper blended together so the melon seeds are the only other thing you need to add.",
        "price": 12.25,
        "stock_quantity": 20,
        "images": ["spices-sauces-kit-03-a.jpg", "spices-sauces-kit-03-b.jpg", "spices-sauces-kit-03-c.jpg"],
    },
    {
        "name": "Pepper Soup Spice Kit",
        "category": "Spices & Sauce Kits",
        "description": "A warming blend of uziza, calabash nutmeg, and pepper soup spice for the classic Nigerian pepper soup, good with goat meat, chicken, or fish.",
        "price": 10.75,
        "stock_quantity": 20,
        "images": ["spices-sauces-kit-04-a.jpg", "spices-sauces-kit-04-b.jpg"],
    },
    {
        "name": "Ogbono Soup Starter Kit",
        "category": "Spices & Sauce Kits",
        "description": "Ground ogbono seeds paired with the stock and pepper blend needed to get the soup's signature draw right on the first try, a shortcut for one of the trickier soups to get consistent.",
        "price": 13.00,
        "stock_quantity": 18,
        "images": ["spices-sauces-kit-05-a.jpg", "spices-sauces-kit-05-b.jpg", "spices-sauces-kit-05-c.jpg"],
    },
    {
        "name": "Efo Riro Seasoning Blend",
        "category": "Spices & Sauce Kits",
        "description": "A seasoning blend built for efo riro, pepper, crayfish, and stock, so the vegetable soup base is ready before the spinach even hits the pot.",
        "price": 10.50,
        "stock_quantity": 20,
        "images": ["spices-sauces-kit-06-a.jpg", "spices-sauces-kit-06-b.jpg"],
    },
    {
        "name": "Banga Soup Spice Kit",
        "category": "Spices & Sauce Kits",
        "description": "The spice blend behind banga soup's distinct flavour, measured out and ready to combine with palm fruit concentrate.",
        "price": 13.50,
        "stock_quantity": 15,
        "images": ["spices-sauces-kit-07-a.jpg", "spices-sauces-kit-07-b.jpg"],
    },
    {
        "name": "Ata Rodo Pepper Blend",
        "category": "Spices & Sauce Kits",
        "description": "A dried and ground scotch bonnet pepper blend, the base heat behind most Nigerian stews and sauces, for anyone who wants real heat without roasting fresh peppers themselves.",
        "price": 8.99,
        "stock_quantity": 25,
        "images": ["spices-sauces-kit-08-a.jpg", "spices-sauces-kit-08-b.jpg"],
    },
    {
        "name": "Native Curry & Thyme Blend",
        "category": "Spices & Sauce Kits",
        "description": "A curry and thyme forward seasoning blend used across native soups and stews, a pantry staple rather than a single-dish specialty.",
        "price": 9.50,
        "stock_quantity": 22,
        "images": ["spices-sauces-kit-09-a.jpg", "spices-sauces-kit-09-b.jpg", "spices-sauces-kit-09-c.jpg"],
    },
    # ===== Ankara Fabrics =====
    {
        "name": "Kente-Inspired Ankara Bundle",
        "category": "Ankara Fabrics",
        "description": "Six yards of 100% cotton wax print fabric with a bold, Kente-influenced geometric layout. Enough for two full outfits or one outfit with a matching headwrap, cut to order from stock sourced directly from local printers.",
        "price": 32.00, "stock_quantity": 25, "is_featured": True,
        "images": ["ankara-fabrics-01-a.jpg", "ankara-fabrics-01-b.jpg"],
    },
    {
        "name": "Adire Sunburst Wax Print",
        "category": "Ankara Fabrics",
        "description": "A radiant wax print bundle inspired by traditional Adire dye patterns, six yards of breathable cotton with a hand that holds tailored seams well. A strong pick for a statement gown or agbada lining.",
        "price": 29.50, "stock_quantity": 22,
        "images": ["ankara-fabrics-02-a.jpg", "ankara-fabrics-02-b.jpg"],
    },
    {
        "name": "Heritage Bloom Ankara Roll",
        "category": "Ankara Fabrics",
        "description": "Six yards of floral-motif wax print, a softer, more everyday pattern than our bolder bundles. Machine washable on cold, colours set to resist early fading with proper care.",
        "price": 27.75, "stock_quantity": 20,
        "images": ["ankara-fabrics-03-a.jpg", "ankara-fabrics-03-b.jpg"],
    },
    {
        "name": "Midnight Diamond Wax Print",
        "category": "Ankara Fabrics",
        "description": "A striking diamond-patterned wax print in a deep, dramatic colourway, six yards of premium cotton weight. Our most requested bundle for evening wear and formal aso-ebi sets.",
        "price": 34.00, "stock_quantity": 18, "is_featured": True,
        "images": ["ankara-fabrics-04-a.jpg", "ankara-fabrics-04-b.jpg", "ankara-fabrics-04-c.jpg"],
    },
    {
        "name": "Modern Wave Ankara Bundle",
        "category": "Ankara Fabrics",
        "description": "A contemporary take on wax print with a flowing, wave-like layout, six yards of cotton suited to structured modern silhouettes as much as traditional cuts.",
        "price": 30.00, "stock_quantity": 20,
        "images": ["ankara-modern-01-a.png", "ankara-modern-01-b.png"],
    },
    {
        "name": "Contour Line Wax Print",
        "category": "Ankara Fabrics",
        "description": "Clean, linear patterning on a six-yard wax print bundle, a good match for anyone wanting the authenticity of Ankara with a more minimal, modern print style.",
        "price": 28.50, "stock_quantity": 18,
        "images": ["ankara-modern-02-a.png", "ankara-modern-02-b.png"],
    },
    {
        "name": "Urban Pulse Ankara Roll",
        "category": "Ankara Fabrics",
        "description": "A high-energy modern print on premium cotton wax fabric, six yards, designed for pieces meant to stand out in a crowd.",
        "price": 31.25, "stock_quantity": 16,
        "images": ["ankara-modern-03-a.png", "ankara-modern-03-b.png"],
    },
    {
        "name": "Minimalist Grid Wax Print",
        "category": "Ankara Fabrics",
        "description": "A restrained, grid-based print for anyone who wants Ankara's texture and heritage without a busy pattern. Six yards, single main shot for this one.",
        "price": 26.00, "stock_quantity": 24,
        "images": ["ankara-modern-04.png"],
    },
    {
        "name": "Abstract Bloom Ankara",
        "category": "Ankara Fabrics",
        "description": "An abstract floral wax print bundle, six yards of cotton with a soft drape, well suited to both tailored and loose-fit garments.",
        "price": 27.00, "stock_quantity": 20,
        "images": ["ankara-modern-05.png"],
    },
    {
        "name": "Metro Ankara Bundle",
        "category": "Ankara Fabrics",
        "description": "A modern city-inspired print on six yards of quality wax cotton, part of our contemporary Ankara line for buyers who want a fresher take on a classic fabric.",
        "price": 29.99, "stock_quantity": 19,
        "images": ["ankara-modern-06-a.png", "ankara-modern-06-b.png"],
    },
    {
        "name": "Asoebi Celebration Bundle",
        "category": "Ankara Fabrics",
        "description": "Sold in bulk-friendly six-yard cuts specifically for group aso-ebi orders, so everyone at the celebration matches. Order multiples from the same batch to guarantee colour consistency across a whole party.",
        "price": 36.00, "stock_quantity": 30, "is_featured": True,
        "images": ["asoebi-01-a.png", "asoebi-01-b.png"],
    },
    {
        "name": "Heritage Lace Fabric",
        "category": "Ankara Fabrics",
        "description": "A premium lace fabric bundle available in five colourways. Six yards per order, a popular choice for occasion wear where a lighter, more textured fabric than wax print is wanted.",
        "price": 38.00, "stock_quantity": 15, "is_featured": True,
        "images": [
            "fabric-lace-white-0001-a.png", "fabric-lace-blue-0001-b.png",
            "fabric-lace-pink-0001-c.png", "fabric-lace-green-0001-d.png",
            "fabric-lace-purple-0001-e.png",
        ],
        "variants": [
            {"type": "colour", "value": "White", "stock_quantity": 8},
            {"type": "colour", "value": "Blue", "stock_quantity": 6},
            {"type": "colour", "value": "Pink", "stock_quantity": 5},
            {"type": "colour", "value": "Green", "stock_quantity": 7},
            {"type": "colour", "value": "Purple", "stock_quantity": 4},
        ],
    },
    {
        "name": "Ijebu Wax Print Bundle",
        "category": "Ankara Fabrics",
        "description": "Named for the Ijebu tradition of fine wax print craftsmanship, this six-yard bundle is one of our most authentic pieces, printed using techniques passed down through generations of local artisans.",
        "price": 33.50, "stock_quantity": 20, "is_featured": True,
        "images": ["ijebu-wax-print-010.a.png", "ijebu-wax-print-010.b.png"],
    },
    {
        "name": "New Arrival Wax Print Bundle",
        "category": "Ankara Fabrics",
        "description": "One of our newest wax print arrivals, six yards of fresh stock just brought into the catalogue. Get it before this run sells out and the next design takes its place.",
        "price": 30.50, "stock_quantity": 28,
        "images": ["newest-wax-print-050-a.png", "newest-wax-print-050-b.png"],
    },
    {
        "name": "Ile-Ife Lace Bundle",
        "category": "Ankara Fabrics",
        "description": "A premium lace-style fabric bundle from our regional collection, named for the historic city of Ile-Ife. Six yards, suited to occasion wear where a finer texture than wax print cotton is preferred.",
        "price": 35.00, "stock_quantity": 14,
        "images": ["african-wax-fabric-lace-print-luxury-000091.png"],
    },
    {
        "name": "Oyo Heritage Lace",
        "category": "Ankara Fabrics",
        "description": "Part of our city-named lace collection, six yards of premium fabric honouring the historic Oyo region, well suited to formal and celebration wear.",
        "price": 34.50, "stock_quantity": 15,
        "images": ["african-wax-fabric-lace-print-luxury-000092.png"],
    },
    {
        "name": "Ondo Luxury Lace",
        "category": "Ankara Fabrics",
        "description": "Six yards of premium lace-style fabric from our regional collection, named for Ondo. A finer weight than our standard wax prints, popular for special occasions.",
        "price": 33.00, "stock_quantity": 16,
        "images": ["african-wax-fabric-lace-print-luxury-000093.png"],
    },
    {
        "name": "Ekiti Royal Lace",
        "category": "Ankara Fabrics",
        "description": "Named for the Ekiti region, this six-yard lace bundle is one of our higher-end fabric offerings, chosen often for weddings and formal celebrations.",
        "price": 36.50, "stock_quantity": 12,
        "images": ["african-wax-fabric-lace-print-luxury-000094.png"],
    },
    {
        "name": "Osun Golden Lace",
        "category": "Ankara Fabrics",
        "description": "Six yards of premium lace fabric from our city-named collection, honouring the Osun region. A lighter weight fabric, well suited to warm-climate occasion wear.",
        "price": 34.00, "stock_quantity": 15,
        "images": ["african-wax-fabric-lace-print-luxury-000095.png"],
    },
    {
        "name": "Ogun Classic Lace",
        "category": "Ankara Fabrics",
        "description": "A six-yard lace bundle named for the Ogun region, part of our premium fabric range for buyers wanting something beyond standard wax print cotton.",
        "price": 32.50, "stock_quantity": 17,
        "images": ["african-wax-fabric-lace-print-luxury-000096.png"],
    },
    {
        "name": "Kwara Elegant Lace",
        "category": "Ankara Fabrics",
        "description": "Six yards of fine lace-style fabric named for the Kwara region, a popular choice for aso-ebi groups wanting a step up from standard cotton wax print.",
        "price": 35.50, "stock_quantity": 13,
        "images": ["african-wax-fabric-lace-print-luxury-000097.png"],
    },
    {
        "name": "Lagos Premium Lace",
        "category": "Ankara Fabrics",
        "description": "The flagship of our city-named lace collection, six yards of our finest available lace fabric, named for Lagos, the commercial heart of the trade this whole catalogue is built on.",
        "price": 37.00, "stock_quantity": 12,
        "images": ["african-wax-fabric-lace-print-luxury-000098.png"],
    },
    {
        "name": "Kano Wax Print Bundle",
        "category": "Ankara Fabrics",
        "description": "Six yards of quality cotton wax print, part of our city-named collection honouring Kano's long trading history in West African textiles.",
        "price": 26.50, "stock_quantity": 22,
        "images": ["ankara-fabric-luxury-61.png"],
    },
    {
        "name": "Kaduna Wax Print Bundle",
        "category": "Ankara Fabrics",
        "description": "A six-yard wax print bundle named for Kaduna, standard cotton weight, suited to everyday tailoring and casual traditional wear alike.",
        "price": 27.00, "stock_quantity": 20,
        "images": ["ankara-fabric-luxury-62.png"],
    },
    {
        "name": "Enugu Wax Print Bundle",
        "category": "Ankara Fabrics",
        "description": "Six yards of cotton wax print named for Enugu, a reliable, everyday fabric choice for buyers building out a basic wardrobe of traditional pieces.",
        "price": 25.75, "stock_quantity": 24,
        "images": ["ankara-fabric-luxury-63.png"],
    },
    {
        "name": "Aba Market Wax Print",
        "category": "Ankara Fabrics",
        "description": "Named for the market city of Aba, this six-yard cotton wax print bundle is one of our better-value everyday fabric options.",
        "price": 24.99, "stock_quantity": 26,
        "images": ["ankara-fabric-luxury-64.png"],
    },
    {
        "name": "Benin City Wax Print",
        "category": "Ankara Fabrics",
        "description": "Six yards of cotton wax print fabric honouring the historic Benin City, standard weight, suited to a wide range of tailoring projects.",
        "price": 28.00, "stock_quantity": 19,
        "images": ["ankara-fabric-luxury-66.png"],
    },
    {
        "name": "Calabar Coastal Wax Print",
        "category": "Ankara Fabrics",
        "description": "A six-yard wax print bundle named for the coastal city of Calabar, part of our regional cotton fabric range.",
        "price": 27.50, "stock_quantity": 21,
        "images": ["ankara-fabric-luxury-67.png"],
    },
    {
        "name": "Abuja Capital Wax Print",
        "category": "Ankara Fabrics",
        "description": "Named for the federal capital, six yards of quality cotton wax print for everyday and semi-formal traditional wear.",
        "price": 29.00, "stock_quantity": 18,
        "images": ["ankara-fabric-luxury-68.png"],
    },
    {
        "name": "Jos Plateau Wax Print",
        "category": "Ankara Fabrics",
        "description": "Six yards of cotton wax print fabric named for the Jos Plateau region, a dependable, everyday-priced piece in our regional collection.",
        "price": 26.25, "stock_quantity": 23,
        "images": ["ankara-fabric-luxury-69.png"],
    },
    {
        "name": "Ibadan Wax Print Bundle",
        "category": "Ankara Fabrics",
        "description": "Named for Ibadan, one of West Africa's largest cities, this six-yard cotton wax print bundle is a solid, versatile everyday choice.",
        "price": 25.50, "stock_quantity": 25,
        "images": ["ankara-fabric-luxury-70.png"],
    },
    {
        "name": "Sokoto Heritage Wax Print",
        "category": "Ankara Fabrics",
        "description": "Six yards of wax print cotton honouring the historic Sokoto region, part of our full regional fabric line.",
        "price": 28.75, "stock_quantity": 17,
        "images": ["ankara-fabric-luxury-71.png"],
    },
    {
        "name": "Warri Delta Wax Print",
        "category": "Ankara Fabrics",
        "description": "Named for the Niger Delta city of Warri, this six-yard cotton wax print bundle rounds out our regional collection with a reliable, everyday fabric option.",
        "price": 27.25, "stock_quantity": 20,
        "images": ["ankara-fabric-luxury-72.png"],
    },
    {
        "name": "Owerri Wax Print Bundle",
        "category": "Ankara Fabrics",
        "description": "Six yards of standard-weight cotton wax print named for Owerri, suited to casual and semi-formal traditional wear alike.",
        "price": 26.75, "stock_quantity": 21,
        "images": ["ankara-fabric-luxury-73.png"],
    },
    {
        "name": "Uyo Coastal Wax Print",
        "category": "Ankara Fabrics",
        "description": "Named for the coastal city of Uyo, six yards of quality cotton wax print, part of our full regional fabric range.",
        "price": 25.99, "stock_quantity": 22,
        "images": ["ankara-fabric-luxury-74.png"],
    },
    {
        "name": "Akure Sunrise Wax Print",
        "category": "Ankara Fabrics",
        "description": "The final piece in our regional wax print series, six yards of cotton fabric named for Akure, closing out one of our most complete fabric collections.",
        "price": 29.50, "stock_quantity": 19,
        "images": ["ankara-fabric-luxury-75.png"],
    },
    # ===== Beads & Jewellery =====
    {
        "name": "Layered Beaded Necklace",
        "category": "Beads & Jewellery",
        "description": "A multi-strand beaded necklace layered for a fuller look without needing to stack separate pieces yourself. Handmade, adjustable clasp.",
        "price": 18.50, "stock_quantity": 20, "is_featured": True,
        "images": ["beads-women-necklace-005-a.png", "beads-women-necklace-005-b.png", "beads-women-necklace-005-c.png"],
    },
    {
        "name": "Crimson Beaded Necklace",
        "category": "Beads & Jewellery",
        "description": "A single-strand beaded necklace in a deep red colourway, handmade and finished with a secure clasp. A simple, versatile everyday piece.",
        "price": 15.00, "stock_quantity": 18,
        "images": ["beads-women-necklace-red-006.png"],
    },
    {
        "name": "Red Wrist Beads Set",
        "category": "Beads & Jewellery",
        "description": "Traditional handmade wrist beads on stretch cord, sold as a set. Comfortable for daily wear, easy to layer with other bracelets.",
        "price": 12.00, "stock_quantity": 30,
        "images": ["beads-women-wrist-red-001-a.png", "beads-women-wrist-red-001-b.png"],
    },
    {
        "name": "Bold Ruby Statement Necklace",
        "category": "Beads & Jewellery",
        "description": "An elegant, statement-sized beaded necklace designed to be the focal point of an outfit rather than a subtle accent. Handmade with a reinforced clasp for the added weight.",
        "price": 24.00, "stock_quantity": 14, "is_featured": True,
        "images": ["bold-reddish-elegant-women-necklace-040.a.png", "bold-reddish-elegant-women-necklace-040.b.png"],
    },
    {
        "name": "Exotic Luxury Necklace",
        "category": "Beads & Jewellery",
        "description": "A richly detailed necklace from our luxury line, combining traditional beadwork with a more formal, occasion-ready finish.",
        "price": 28.00, "stock_quantity": 12,
        "images": ["exotic-luxury-jewelry-women-necklace-a.png", "exotic-luxury-jewelry-women-necklace-b.png"],
    },
    {
        "name": "Gold-Plated Cross Necklace",
        "category": "Beads & Jewellery",
        "description": "A gold-plated cross pendant on a fine chain, a simple, versatile piece that layers well with our beaded necklaces or wears alone.",
        "price": 22.50, "stock_quantity": 16,
        "images": ["luxuru-cross-gold-plated-necklace.png"],
    },
    {
        "name": "Decorative Luxury Cufflinks",
        "category": "Beads & Jewellery",
        "description": "A finely detailed pair of cufflinks for formal traditional wear, agbada and kaftan sleeves especially. Presented as a matched pair.",
        "price": 19.99, "stock_quantity": 20,
        "images": ["luxury-cufflinks-decorative.a.png", "luxury-cufflinks-decorative.b.png"],
    },
    {
        "name": "Emerald & Gold Jewelry Set",
        "category": "Beads & Jewellery",
        "description": "A coordinated three-piece set, watch, earrings, and necklace, in a green and gold colourway. Sold as a complete matching set rather than individual pieces.",
        "price": 42.00, "stock_quantity": 10, "is_featured": True,
        "images": ["luxury-green-golden-set-watch-earrings-neck.jpg"],
    },
    {
        "name": "Geneva Classic Wrist Watch",
        "category": "Beads & Jewellery",
        "description": "A classic-styled wrist watch with a clean dial face, suited to both everyday wear and formal occasions. A dependable staple piece rather than a fashion statement.",
        "price": 38.00, "stock_quantity": 15,
        "images": ["luxury-men-wrist-watch-geneva.png"],
    },
    {
        "name": "Men's Stone Bead Necklace",
        "category": "Beads & Jewellery",
        "description": "A natural stone bead necklace for men, strung on durable cord. Understated enough for daily wear, substantial enough to notice.",
        "price": 17.50, "stock_quantity": 22,
        "images": ["men-beaded-stone-necklace-01-a.jpg", "men-beaded-stone-necklace-01-b.jpg"],
    },
    {
        "name": "Men's Layered Bead Set",
        "category": "Beads & Jewellery",
        "description": "A layered set of men's beaded necklaces, designed to be worn together for a fuller look straight out of the box.",
        "price": 20.00, "stock_quantity": 18, "is_featured": True,
        "images": ["men-jewelry-beads-02-a.jpg", "men-jewelry-beads-02-b.jpg", "men-jewelry-beads-02-c.jpg"],
    },
    {
        "name": "Bohemian Style Men's Beads",
        "category": "Beads & Jewellery",
        "description": "A relaxed, bohemian-influenced beaded necklace for men, mixing bead sizes and textures on a single durable strand.",
        "price": 18.00, "stock_quantity": 20,
        "images": ["men-jewelry-bohemia-style-beads-01-a.jpg", "men-jewelry-bohemia-style-beads-01-b.jpg", "men-jewelry-bohemia-style-beads-01-c.jpg"],
    },
    {
        "name": "Natural Tiger's Eye Bead Bracelet",
        "category": "Beads & Jewellery",
        "description": "A bracelet strung with natural tiger's eye stone beads, unisex in style. Genuine stone, so each piece carries slight natural variation.",
        "price": 16.50, "stock_quantity": 24,
        "images": ["natural-blue-tiger-eye-stone-beads-a.jpg", "natural-blue-tiger-eye-stone-beads-b.jpg"],
    },
    {
        "name": "Radiant Red Beaded Set",
        "category": "Beads & Jewellery",
        "description": "A vibrant beaded jewelry set in a bold red colourway, handmade with a polished, occasion-ready finish.",
        "price": 21.00, "stock_quantity": 16,
        "images": ["shining-red-beads-women.a.png", "shining-red-beads-women.b.png"],
    },
    {
        "name": "Unisex Leather & Bead Wristband",
        "category": "Beads & Jewellery",
        "description": "A wristband combining leather cord with beaded accents, styled to suit men or women equally. Adjustable fit.",
        "price": 13.50, "stock_quantity": 28,
        "images": ["unisex-bead-leather-wrist-wear.jpg"],
    },
    {
        "name": "Acrylic Bead Necklace, Classic Cut",
        "category": "Beads & Jewellery",
        "description": "A lightweight acrylic beaded necklace in a classic, evenly-spaced bead pattern. An affordable everyday piece.",
        "price": 12.50, "stock_quantity": 30,
        "images": ["women-acrylic-beaded-necklace-01.jpg"],
    },
    {
        "name": "Acrylic Bead Necklace, Bold Cut",
        "category": "Beads & Jewellery",
        "description": "A lightweight acrylic beaded necklace with a bolder, larger bead size than our classic cut, for a more noticeable everyday piece.",
        "price": 13.00, "stock_quantity": 28,
        "images": ["women-acrylic-beaded-necklace-02.jpg"],
    },
    {
        "name": "Acrylic Bead Necklace, Petite Cut",
        "category": "Beads & Jewellery",
        "description": "A daintier acrylic beaded necklace with smaller beads, suited to layering with other pieces or wearing alone for a subtler look.",
        "price": 11.99, "stock_quantity": 30,
        "images": ["women-acrylic-beaded-necklace-03.jpg"],
    },
    {
        "name": "Acrylic Bead Necklace, Chunky Cut",
        "category": "Beads & Jewellery",
        "description": "A statement-sized acrylic beaded necklace with a chunky bead profile, built to stand out as the main piece in an outfit.",
        "price": 14.50, "stock_quantity": 22,
        "images": ["women-acrylic-beaded-necklace-04.jpg"],
    },
    {
        "name": "Acrylic Bead Necklace, Delicate Cut",
        "category": "Beads & Jewellery",
        "description": "A fine, delicate acrylic beaded necklace, our lightest option in the acrylic line, well suited to everyday wear.",
        "price": 12.00, "stock_quantity": 26,
        "images": ["women-acrylic-beaded-necklace-05.jpg"],
    },
    {
        "name": "Emerald Pendant Necklace Set",
        "category": "Beads & Jewellery",
        "description": "A pendant necklace set in a green colourway, presented as a coordinated set rather than a single piece. A step up from our everyday acrylic line.",
        "price": 26.50, "stock_quantity": 14,
        "images": ["women-green-pendant-necklace-luxury-set.jpg"],
    },
    {
        "name": "Women's Beaded Jewelry Set",
        "category": "Beads & Jewellery",
        "description": "A coordinated beaded jewelry set for women, handmade and finished to be worn as a complete look straight out of the packaging.",
        "price": 23.00, "stock_quantity": 18, "is_featured": True,
        "images": ["women-jewelry-beads-01-a.jpg", "women-jewelry-beads-01-b.jpg", "women-jewelry-beads-01-c.jpg"],
    },
    # ===== Accessories =====
    {
        "name": "African Print Accent Handbag",
        "category": "Accessories",
        "description": "A handbag featuring African print detailing against a structured base, a versatile everyday piece that carries the collection's identity without being a full fabric bag.",
        "price": 34.00, "stock_quantity": 18, "is_featured": True,
        "images": ["african-stylish-handbag-20507.png"],
    },
    {
        "name": "Everyday Tote Handbag",
        "category": "Accessories",
        "description": "A roomy, structured tote built for daily use, market runs, work, or travel, with enough interior space to actually be useful, not just decorative.",
        "price": 28.50, "stock_quantity": 20,
        "images": ["handbag-20501.png"],
    },
    {
        "name": "Structured Shoulder Handbag",
        "category": "Accessories",
        "description": "A shoulder bag with a firm, structured shape that holds its form even when lightly packed, a reliable everyday carry.",
        "price": 30.00, "stock_quantity": 16,
        "images": ["handbag-20502.png"],
    },
    {
        "name": "Woven Detail Handbag",
        "category": "Accessories",
        "description": "A handbag featuring woven texture detailing, giving it a handcrafted feel alongside a practical, everyday shape.",
        "price": 32.50, "stock_quantity": 15,
        "images": ["handbag-20503.a.png", "handbag-20503.b.png"],
    },
    {
        "name": "Compact Crossbody Handbag",
        "category": "Accessories",
        "description": "A smaller crossbody bag for when you want your hands free, sized for essentials rather than a full day's carry.",
        "price": 24.00, "stock_quantity": 22,
        "images": ["handbag-20504.png"],
    },
    {
        "name": "Classic Satchel Handbag",
        "category": "Accessories",
        "description": "A structured satchel-style handbag with a timeless shape, suited to both casual outings and slightly dressier occasions.",
        "price": 29.00, "stock_quantity": 18,
        "images": ["handbag-20505.png"],
    },
    {
        "name": "Embellished Evening Handbag",
        "category": "Accessories",
        "description": "A smaller, embellished handbag built for evenings out rather than daily carry, a step up from our everyday bag line.",
        "price": 36.00, "stock_quantity": 12, "is_featured": True,
        "images": ["handbag-20506.a.png", "handbag-20506.b.png"],
    },
    {
        "name": "Casual Luxury Handbag",
        "category": "Accessories",
        "description": "A handbag balancing a relaxed, casual shape with premium finishing touches, for buyers who want quality without a formal look.",
        "price": 33.00, "stock_quantity": 16,
        "images": ["women-handbag-casual-luxury.png"],
    },
    {
        "name": "Night Out Clutch Bag",
        "category": "Accessories",
        "description": "A compact clutch sized for a night out, just enough room for the essentials, built to be carried, not slung over a shoulder.",
        "price": 22.50, "stock_quantity": 20,
        "images": ["portable-ladies-handbag-for-nightout-clubbing.png"],
    },
    {
        "name": "Open Heel Sandals",
        "category": "Accessories",
        "description": "A pair of open-heel sandals for warm-weather everyday wear, an easy-to-style option for both casual and semi-dressed-up outfits.",
        "price": 19.99, "stock_quantity": 25,
        "images": ["ladies-open-heal-sandal.png"],
    },
    {
        "name": "Men's Comfort Flip Flops",
        "category": "Accessories",
        "description": "A simple, comfortable pair of men's flip flops for everyday wear around the house or out running errands.",
        "price": 12.99, "stock_quantity": 30,
        "images": ["men-flipflop-nice-sandal.png"],
    },
    {
        "name": "African Print Sandals, Style One",
        "category": "Accessories",
        "description": "Sandals featuring African print detailing on the strap, a casual, everyday shoe that carries the collection's design language down to the footwear.",
        "price": 21.00, "stock_quantity": 20, "is_featured": True,
        "images": ["styled-flip-flops-african-sandal-01.a.png", "styled-flip-flops-african-sandal-01.b.png"],
    },
    {
        "name": "African Print Sandals, Style Two",
        "category": "Accessories",
        "description": "A second print option in our African-print sandal line, same comfortable everyday build with a distinct pattern from Style One.",
        "price": 21.00, "stock_quantity": 20,
        "images": ["styled-flip-flops-african-sandal-02.a.png", "styled-flip-flops-african-sandal-02.b.png"],
    },
    # ===== Homeware =====
    {
        "name": "Mahogany Wood Rolling Pin",
        "category": "Homeware",
        "description": "A 17-inch solid mahogany rolling pin, weighted for even pressure on dough for chin chin, meat pie, or any home baking that needs a proper rolling surface.",
        "price": 16.50, "stock_quantity": 25,
        "images": ["17inch-mahogany-rolling-pin-a.png", "17inch-mahogany-rolling-pin-b.png"],
    },
    {
        "name": "21-Piece Ceramic Nonstick Cookware Set",
        "category": "Homeware",
        "description": "A complete 21-piece ceramic nonstick cookware set covering pots, pans, and lids for a full kitchen setup in one purchase. Ceramic coating means no metal utensil scratching worries with normal use.",
        "price": 89.00, "stock_quantity": 10, "is_featured": True,
        "images": ["21pieces-ceramic-nonstick-cookware-a.png", "21pieces-ceramic-nonstick-cookware-b.png"],
    },
    {
        "name": "360° Rotating Cosmetics Organizer",
        "category": "Homeware",
        "description": "A rotating storage unit for makeup and small cosmetics, keeping a dresser or bathroom counter organized with everything visible and reachable at a spin.",
        "price": 22.00, "stock_quantity": 18,
        "images": ["360-rotating-makeup-cosmetics-storage-a.png", "360-rotating-makeup-cosmetics-storage-b.png"],
    },
    {
        "name": "Airtight Meal Prep Container Set",
        "category": "Homeware",
        "description": "A set of six airtight plastic containers for meal prep and leftovers, stackable for fridge or pantry storage.",
        "price": 18.99, "stock_quantity": 22,
        "images": ["6-containers-airtight-plastic-meal-bowls.png"],
    },
    {
        "name": "6-Sided Kitchen Grater",
        "category": "Homeware",
        "description": "A multi-surface grater with six different grating sides in one tool, covers everything from fine zest to coarse vegetable shreds without needing separate graters.",
        "price": 11.50, "stock_quantity": 30,
        "images": ["6-sided-grater-a.png", "6-sided-grater-b.png"],
    },
    {
        "name": "7-Piece Spice Shaker Combo",
        "category": "Homeware",
        "description": "A seven-piece set of swivel-base spice shakers, keeping a countertop's worth of seasonings organized and easy to grab mid-cook.",
        "price": 19.50, "stock_quantity": 20,
        "images": ["7pieces-swivel-base-spice-shaker-combo.png"],
    },
    {
        "name": "Breathable Comfort Pillow",
        "category": "Homeware",
        "description": "A soft, breathable pillow designed for consistent comfort through the night, machine washable cover.",
        "price": 21.00, "stock_quantity": 24,
        "images": ["Breath-pillow-soft-comfortable-a.png", "Breath-pillow-soft-comfortable-b.png"],
    },
    {
        "name": "Fine Mesh Sieve Set",
        "category": "Homeware",
        "description": "A set of fine mesh sieves for filtering, straining, and sifting, an everyday kitchen tool that earns its space in any drawer.",
        "price": 9.99, "stock_quantity": 28,
        "images": ["Mesh-sieves-for-filtering.png"],
    },
    {
        "name": "Stainless Steel Buffet Serving Tongs",
        "category": "Homeware",
        "description": "Sturdy stainless steel serving tongs built for buffet-style serving, fish and larger cuts especially, where a flimsy tool won't hold up.",
        "price": 10.50, "stock_quantity": 26,
        "images": ["Steel-serving-tong-for-buffet-fish.png"],
    },
    {
        "name": "Luxury Dining Tablecloth",
        "category": "Homeware",
        "description": "A decorative dining tablecloth for special-occasion table settings, finished to hold its shape and drape well over a full-sized table.",
        "price": 24.00, "stock_quantity": 15,
        "images": ["Tablecloth-dining-luxurious-decor.png"],
    },
    {
        "name": "Diamond Pattern Drinkware Set",
        "category": "Homeware",
        "description": "A set of patterned glass cups for juice or everyday drinks, a small but noticeable upgrade to a table setting.",
        "price": 17.00, "stock_quantity": 20,
        "images": ["diamond-pattern-drinkware-cups-for-juice.png"],
    },
    {
        "name": "Enamel Stew Pot & Utensil Set",
        "category": "Homeware",
        "description": "A multifunctional enamel stew pot paired with matching utensils, built for the long, slow cooking that native soups and stews need.",
        "price": 45.00, "stock_quantity": 12, "is_featured": True,
        "images": ["exquisite-enamel-multifunctional-stew-pots-utensils-a.png", "exquisite-enamel-multifunctional-stew-pots-utensils-b.png"],
    },
    {
        "name": "Polished Stainless Cutlery Box Set",
        "category": "Homeware",
        "description": "A complete cutlery set presented in its own storage box, glossy polished finish, ready to use straight out of the packaging or give as a gift.",
        "price": 32.00, "stock_quantity": 16,
        "images": ["glossy-polished-stainlesscutlery-box-a.png", "glossy-polished-stainlesscutlery-box-b.png"],
    },
    {
        "name": "Complete Kitchen Tool Set",
        "category": "Homeware",
        "description": "A full set of everyday cooking tools, spatula, spoon, and tongs included, covering the basics most kitchens reach for daily.",
        "price": 20.50, "stock_quantity": 22,
        "images": ["kitchenware-set-including-spatula-spoon-tong-cooking-tool-a.png", "kitchenware-set-including-spatula-spoon-tong-cooking-tool-b.png"],
    },
    {
        "name": "Milton 3-Piece Thermal Casserole Set",
        "category": "Homeware",
        "description": "A three-piece thermal casserole set that keeps food warm for hours after cooking, useful for parties, gatherings, or just a slower family dinner.",
        "price": 38.00, "stock_quantity": 14, "is_featured": True,
        "images": ["milton-3-pieces-casserole-set-thermal-cookin-pot-a.png", "milton-3-pieces-casserole-set-thermal-cookin-pot-b.png"],
    },
    {
        "name": "Practical Kitchen Knife Set",
        "category": "Homeware",
        "description": "A set of everyday kitchen knives covering the basic cutting tasks a home kitchen actually needs, no oversized specialty blades included.",
        "price": 27.50, "stock_quantity": 18,
        "images": ["practical-knife-set-utensils.png"],
    },
    {
        "name": "Kitchen & Dining Table Linen Set",
        "category": "Homeware",
        "description": "A coordinated table linen set for the kitchen or dining table, a practical finishing touch for everyday meals as well as guests.",
        "price": 15.99, "stock_quantity": 20,
        "images": ["table-kitechen-flat-2d-banner-linens.png"],
    },
    {
        "name": "Mixed Pattern Bedspread",
        "category": "Homeware",
        "description": "A bedspread combining mixed patterns for a layered, collected look without needing to coordinate separate pieces yourself.",
        "price": 34.00, "stock_quantity": 16,
        "images": ["bedspread-mix-a.png", "bedspread-mix-b.png"],
    },
    {
        "name": "Soft Textured Cushion Cover Set",
        "category": "Homeware",
        "description": "A set of four textured cushion covers, soft to the touch, an easy way to refresh a living room or bedroom without buying new cushions outright.",
        "price": 19.00, "stock_quantity": 24,
        "images": ["cushion-textured-4-case-soft-a.png", "cushion-textured-4-case-soft-b.png"],
    },
    {
        "name": "King Size Cotton Coverlet",
        "category": "Homeware",
        "description": "A lightweight cotton coverlet sized for king beds, in a warm orange tone, suited to warmer climates or as a lighter layer over a heavier duvet.",
        "price": 36.00, "stock_quantity": 14,
        "images": ["orange-lightweight-bed-coverlet-kingsize-cotton-a.png", "orange-lightweight-bed-coverlet-kingsize-cotton-b.png"],
    },
    {
        "name": "Printed Quality Bedspread",
        "category": "Homeware",
        "description": "A patterned bedspread finished to a higher quality standard than a basic throw, sized to cover a full bed with drop on both sides.",
        "price": 31.00, "stock_quantity": 16,
        "images": ["printed-quality-bedspread-a.png", "printed-quality-bedspread-b.png"],
    },
    {
        "name": "Red Luxury Duvet Set",
        "category": "Homeware",
        "description": "A duvet set in a rich red colourway, positioned as a step up from our standard bedding line for anyone wanting a more premium bedroom finish.",
        "price": 48.00, "stock_quantity": 10, "is_featured": True,
        "images": ["red-luxury-bed-duvet-a.png", "red-luxury-bed-duvet-b.png"],
    },
    {
        "name": "4-Piece Thickened Towel Set",
        "category": "Homeware",
        "description": "A set of four thickened, absorbent towels, sized for everyday bathroom use, built to hold up to regular washing without thinning out quickly.",
        "price": 26.00, "stock_quantity": 20,
        "images": ["thickened-super-towel-set-4pieces-a.png", "thickened-super-towel-set-4pieces-b.png"],
    },
    # ===== Traditional Wear =====
    {
        "name": "African Print Fabric Cap, Style One",
        "category": "Traditional Wear",
        "description": "A structured cap made from genuine African print fabric, a small but authentic finishing piece for traditional outfits.",
        "price": 14.00, "stock_quantity": 25,
        "images": ["african-style-fabric-cap-01-a.png", "african-style-fabric-cap-01-b.png"],
    },
    {
        "name": "African Print Fabric Cap, Style Two",
        "category": "Traditional Wear",
        "description": "A second print option in our fabric cap line, same structured build with a distinct pattern from Style One.",
        "price": 14.00, "stock_quantity": 20,
        "images": ["african-style-fabric-cap-02.png"],
    },
    {
        "name": "African Print Fabric Cap, Style Three",
        "category": "Traditional Wear",
        "description": "A third fabric cap option rounding out our cap collection, structured fit with genuine African print fabric.",
        "price": 14.00, "stock_quantity": 20,
        "images": ["african-style-fabric-cap-03-a.png", "african-style-fabric-cap-03-b.png"],
    },
    {
        "name": "Wax Print Shirt & Shorts Set",
        "category": "Traditional Wear",
        "description": "A coordinated shirt and shorts set in genuine wax print fabric, a relaxed, warm-weather traditional outfit for men.",
        "price": 32.00, "stock_quantity": 18, "is_featured": True,
        "images": ["african-waxprint-men-shirt-shortpant.png"],
    },
    {
        "name": "Kids' Ankara Casual Outfit",
        "category": "Traditional Wear",
        "description": "A casual Ankara outfit sized for children, comfortable everyday wear that still carries real print fabric rather than a printed imitation.",
        "price": 22.00, "stock_quantity": 22,
        "images": ["fabric-casual-kids-a.png", "fabric-casual-kids-b.png"],
    },
    {
        "name": "Ankara Fabric Headband",
        "category": "Traditional Wear",
        "description": "A simple headband made from Ankara fabric offcuts, an easy way to add a pop of pattern to any outfit.",
        "price": 6.50, "stock_quantity": 35,
        "images": ["fabric-headband-ankara.png"],
    },
    {
        "name": "Women's Kente Attire Set",
        "category": "Traditional Wear",
        "description": "A complete women's attire set in kente-inspired wax print, styled as a full coordinated outfit rather than separate pieces.",
        "price": 45.00, "stock_quantity": 14, "is_featured": True,
        "images": ["kente-attire-wax-women-888-set.png"],
    },
    {
        "name": "Men's Kente Print Shirt",
        "category": "Traditional Wear",
        "description": "A men's shirt cut from kente-print fabric, smart enough for semi-formal occasions while staying comfortable for everyday wear.",
        "price": 26.00, "stock_quantity": 20,
        "images": ["kente-cloth-men-shirt-a.png", "kente-cloth-men-shirt-b.png"],
    },
    {
        "name": "Men's Agbada Cultural Wear",
        "category": "Traditional Wear",
        "description": "A traditional agbada set for men, flowing outer robe over a coordinated inner outfit, worn for weddings, naming ceremonies, and formal cultural events.",
        "price": 68.00, "stock_quantity": 10, "is_featured": True,
        "images": ["men-agbada-cultural-wear-a.jpg", "men-agbada-cultural-wear-b.jpg"],
    },
    {
        "name": "Agbada Danshiki, Black (Full Length)",
        "category": "Traditional Wear",
        "description": "A full-length agbada danshiki in black, a formal traditional outfit suited to weddings and major cultural occasions.",
        "price": 62.00, "stock_quantity": 12,
        "images": ["men-agbada-danshiki-black-01.jpg"],
    },
    {
        "name": "Agbada Danshiki, Black (Short Set)",
        "category": "Traditional Wear",
        "description": "The shorter-cut version of our black agbada danshiki, a lighter, more casual take on the same design for warmer days or less formal events.",
        "price": 45.00, "stock_quantity": 16,
        "images": ["men-agbada-danshiki-black-short-01.jpg"],
    },
    {
        "name": "Agbada Danshiki, Purple (Full Length)",
        "category": "Traditional Wear",
        "description": "A full-length agbada danshiki in a rich purple, formal traditional wear for weddings and ceremonies.",
        "price": 62.00, "stock_quantity": 12,
        "images": ["men-agbada-danshiki-purple-01.jpg"],
    },
    {
        "name": "Agbada Danshiki, Purple (Short Set)",
        "category": "Traditional Wear",
        "description": "The shorter-cut version of our purple agbada danshiki, a lighter, more casual alternative for less formal occasions.",
        "price": 45.00, "stock_quantity": 16,
        "images": ["men-agbada-danshiki-purple-short-01.jpg"],
    },
    {
        "name": "Agbada Danshiki, White",
        "category": "Traditional Wear",
        "description": "A classic white agbada danshiki, a traditional choice for celebrations and formal cultural events.",
        "price": 62.00, "stock_quantity": 12, "is_featured": True,
        "images": ["men-agbada-danshiki-white-01.jpg"],
    },
    {
        "name": "Agbada Danshiki, Yellow (Full Length)",
        "category": "Traditional Wear",
        "description": "A full-length agbada danshiki in a bold yellow, standing out at any celebration it's worn to.",
        "price": 62.00, "stock_quantity": 10,
        "images": ["men-agbada-danshiki-yellow-01.jpg"],
    },
    {
        "name": "Agbada Danshiki, Yellow (Short Set)",
        "category": "Traditional Wear",
        "description": "The shorter-cut version of our yellow agbada danshiki, same bold colour in a more casual, everyday-friendly length.",
        "price": 45.00, "stock_quantity": 14,
        "images": ["men-agbada-danshiki-yellow-short-01.jpg"],
    },
    {
        "name": "Pink Embroidered Agbada Robe",
        "category": "Traditional Wear",
        "description": "An agbada robe in pink with detailed embroidery work, a more decorative option for buyers wanting extra detail on top of the traditional silhouette.",
        "price": 70.00, "stock_quantity": 8, "is_featured": True,
        "images": ["men-agbada-embroidery-robe-pink.jpg"],
    },
    {
        "name": "Agbada Silhouette Robe",
        "category": "Traditional Wear",
        "description": "A traditional agbada silhouette robe, available in two colourways. Same flowing cut and formal styling in either purple or yellow.",
        "price": 65.00, "stock_quantity": 16,
        "images": ["men-agbada-sihouette-robe-01-a-purple.jpg", "men-agbada-sihouette-robe-01-b-yellow.jpg"],
        "variants": [
            {"type": "colour", "value": "Purple", "stock_quantity": 8},
            {"type": "colour", "value": "Yellow", "stock_quantity": 8},
        ],
    },
    {
        "name": "Elegant Textured Robe, Grey",
        "category": "Traditional Wear",
        "description": "A grey robe with a subtle textured finish, a more understated formal option than our brighter agbada colourways.",
        "price": 58.00, "stock_quantity": 12,
        "images": ["men-elegant-style-texture-robe-grey.jpg"],
    },
    {
        "name": "Men's Sleeveless Cultural Top",
        "category": "Traditional Wear",
        "description": "A sleeveless cultural top in traditional fabric, a lighter layering piece for warmer climates or casual cultural wear.",
        "price": 24.00, "stock_quantity": 20,
        "images": ["men-fabric-sleeveless-cultural.png"],
    },
    {
        "name": "Men's Kente Shirt Gown",
        "category": "Traditional Wear",
        "description": "A longer-length kente shirt gown, sitting between a standard shirt and a full agbada in formality.",
        "price": 40.00, "stock_quantity": 14,
        "images": ["men-kente-shirt-gown-006.png"],
    },
    {
        "name": "Navy Agbada Attire",
        "category": "Traditional Wear",
        "description": "A navy agbada set, a versatile darker colourway suited to both daytime and evening formal occasions.",
        "price": 64.00, "stock_quantity": 10,
        "images": ["men-navy-agbada-attire-01.jpg"],
    },
    {
        "name": "Artistic Print Men's Shirt",
        "category": "Traditional Wear",
        "description": "A men's shirt in a bold, artistic African print, for buyers wanting something more visually striking than a standard pattern.",
        "price": 27.00, "stock_quantity": 18,
        "images": ["men-picasson-african-style-008-a.png", "men-picasson-african-style-008-b.png"],
    },
    {
        "name": "Vintage Style Men's Shirt",
        "category": "Traditional Wear",
        "description": "A men's shirt with a vintage-inspired cut and pattern, a nod to earlier decades of West African fashion.",
        "price": 25.00, "stock_quantity": 20,
        "images": ["men-vintage-shirt-a.jpg", "men-vintage-shirt-b.jpg"],
    },
    {
        "name": "Wax Print Casual Shirt",
        "category": "Traditional Wear",
        "description": "A relaxed, everyday shirt in genuine wax print cotton, easy to dress up or down depending on the occasion.",
        "price": 23.50, "stock_quantity": 22,
        "images": ["men-wax-casual-shirt-0007-a.png", "men-wax-casual-shirt-0007-b.png"],
    },
    {
        "name": "Dashiki Short Sleeve T-Shirt, Blue",
        "category": "Traditional Wear",
        "description": "A short sleeve dashiki-print t-shirt in blue, casual and comfortable enough for daily wear while still carrying real cultural print detail.",
        "price": 18.00, "stock_quantity": 26, "is_featured": True,
        "images": ["print-short-sleeve-t-shirt-dashiki-blue-men.png"],
    },
]

REVIEWER_USERNAMES = [
    "amaka_t", "kwame_o", "ngozi_b", "tunde_f", "aisha_r", "chidi_m", "folake_s", "ebuka_n",
]

# Grouped by rating so a 5-star review never accidentally reads lukewarm.
REVIEW_POOL = {
    5: [
        ("Exactly as described", "This is exactly what I expected, great quality and arrived well packaged."),
        ("Really happy with this", "Bought this as a gift and ended up keeping it for myself instead."),
        ("Will buy again", "Second time ordering this one. Consistent quality every time."),
    ],
    4: [
        ("Good quality", "Solid product, does exactly what it says. Minor delay in delivery but worth the wait."),
        ("Would recommend", "Good value for the price. Colour is slightly different in person but still nice."),
    ],
    3: [
        ("It's okay", "Does the job but nothing special. Packaging could be better."),
        ("Decent for the price", "Fair quality for what I paid. Might try a different variant next time."),
    ],
}
