"""
Seed data for the seed_products management command. Image filenames
below reference files expected in seed_images/ just as they were
downloaded and name.  Categories and products
get added incrementally. """

CATEGORIES = [
    {"name": "Ankara Fabrics", "description": "Authentic wax print and lace fabric bundles, sold by the yard."},
    {"name": "Spices & Sauce Kits", "description": "Pre-measured spice blends for authentic West African cooking."},
    {"name": "Homeware", "description": "Kitchen, dining, and bedding pieces for the home."},
    {"name": "Beads & Jewellery", "description": "Handmade beaded and traditional jewellery for men and women."},
    {"name": "Accessories", "description": "Bags and footwear with West African design influence."},
    {"name": "Traditional Wear", "description": "Ready-to-wear traditional and cultural clothing."},
]

PRODUCTS = [
    {
        "name": "Jollof Rice Spice Kit",
        "category": "Spices & Sauce Kits",
        "description": "A pre-measured blend of smoked paprika, thyme, curry powder, and dried chili built specifically for party-style jollof rice. Just add tomatoes, pepper, and rice for the real thing without hunting down eight separate jars.",
        "price": 11.50,
        "stock_quantity": 30,
        "is_featured": True,
        "images": ["spices-sauces-kit-01-a.jpg", "spices-sauces-kit-01-b.jpg"],
    },
    {
        "name": "Suya Spice Blend (Yaji)",
        "category": "Spices & Sauce Kits",
        "description": "A ground peanut and pepper suya spice mix, the same blend used by roadside suya sellers across Nigeria. Rub it onto grilled beef, chicken, or even vegetables for a smoky, peppery crust.",
        "price": 9.99,
        "stock_quantity": 25,
        "is_featured": True,
        "images": ["spices-sauces-kit-02-a.jpg", "spices-sauces-kit-02-b.jpg"],
    },
    {
        "name": "Egusi Soup Spice Mix",
        "category": "Spices & Sauce Kits",
        "description": "The seasoning base for a proper pot of egusi soup, ground crayfish, stock cubes, and pepper blended together so the melon seeds are the only other thing you need to add.",
        "price": 12.25,
        "stock_quantity": 20,
        "images": ["spices-sauces-kit-03-a.jpg", "spices-sauces-kit-03-b.jpg", "spices-sauces-kit-03-c.jpg"],
    },
    {
        "name": "Pepper Soup Spice Kit",
        "category": "Spices & Sauce Kits",
        "description": "A warming blend of uziza, calabash nutmeg, and pepper soup spice for the classic Nigerian pepper soup, good with goat meat, chicken, or fish.",
        "price": 10.75,
        "stock_quantity": 20,
        "images": ["spices-sauces-kit-04-a.jpg", "spices-sauces-kit-04-b.jpg"],
    },
    {
        "name": "Ogbono Soup Starter Kit",
        "category": "Spices & Sauce Kits",
        "description": "Ground ogbono seeds paired with the stock and pepper blend needed to get the soup's signature draw right on the first try, a shortcut for one of the trickier soups to get consistent.",
        "price": 13.00,
        "stock_quantity": 18,
        "images": ["spices-sauces-kit-05-a.jpg", "spices-sauces-kit-05-b.jpg", "spices-sauces-kit-05-c.jpg"],
    },
    {
        "name": "Efo Riro Seasoning Blend",
        "category": "Spices & Sauce Kits",
        "description": "A seasoning blend built for efo riro, pepper, crayfish, and stock, so the vegetable soup base is ready before the spinach even hits the pot.",
        "price": 10.50,
        "stock_quantity": 20,
        "images": ["spices-sauces-kit-06-a.jpg", "spices-sauces-kit-06-b.jpg"],
    },
    {
        "name": "Banga Soup Spice Kit",
        "category": "Spices & Sauce Kits",
        "description": "The spice blend behind banga soup's distinct flavour, measured out and ready to combine with palm fruit concentrate.",
        "price": 13.50,
        "stock_quantity": 15,
        "images": ["spices-sauces-kit-07-a.jpg", "spices-sauces-kit-07-b.jpg"],
    },
    {
        "name": "Ata Rodo Pepper Blend",
        "category": "Spices & Sauce Kits",
        "description": "A dried and ground scotch bonnet pepper blend, the base heat behind most Nigerian stews and sauces, for anyone who wants real heat without roasting fresh peppers themselves.",
        "price": 8.99,
        "stock_quantity": 25,
        "images": ["spices-sauces-kit-08-a.jpg", "spices-sauces-kit-08-b.jpg"],
    },
    {
        "name": "Native Curry & Thyme Blend",
        "category": "Spices & Sauce Kits",
        "description": "A curry and thyme forward seasoning blend used across native soups and stews, a pantry staple rather than a single-dish specialty.",
        "price": 9.50,
        "stock_quantity": 22,
        "images": ["spices-sauces-kit-09-a.jpg", "spices-sauces-kit-09-b.jpg", "spices-sauces-kit-09-c.jpg"],
    },
        # ===== Ankara Fabrics =====
    {
        "name": "Kente-Inspired Ankara Bundle",
        "category": "Ankara Fabrics",
        "description": "Six yards of 100% cotton wax print fabric with a bold, Kente-influenced geometric layout. Enough for two full outfits or one outfit with a matching headwrap, cut to order from stock sourced directly from local printers.",
        "price": 32.00, "stock_quantity": 25, "is_featured": True,
        "images": ["ankara-fabrics-01-a.jpg", "ankara-fabrics-01-b.jpg"],
    },
    {
        "name": "Adire Sunburst Wax Print",
        "category": "Ankara Fabrics",
        "description": "A radiant wax print bundle inspired by traditional Adire dye patterns, six yards of breathable cotton with a hand that holds tailored seams well. A strong pick for a statement gown or agbada lining.",
        "price": 29.50, "stock_quantity": 22,
        "images": ["ankara-fabrics-02-a.jpg", "ankara-fabrics-02-b.jpg"],
    },
    {
        "name": "Heritage Bloom Ankara Roll",
        "category": "Ankara Fabrics",
        "description": "Six yards of floral-motif wax print, a softer, more everyday pattern than our bolder bundles. Machine washable on cold, colours set to resist early fading with proper care.",
        "price": 27.75, "stock_quantity": 20,
        "images": ["ankara-fabrics-03-a.jpg", "ankara-fabrics-03-b.jpg"],
    },
    {
        "name": "Midnight Diamond Wax Print",
        "category": "Ankara Fabrics",
        "description": "A striking diamond-patterned wax print in a deep, dramatic colourway, six yards of premium cotton weight. Our most requested bundle for evening wear and formal aso-ebi sets.",
        "price": 34.00, "stock_quantity": 18, "is_featured": True,
        "images": ["ankara-fabrics-04-a.jpg", "ankara-fabrics-04-b.jpg", "ankara-fabrics-04-c.jpg"],
    },
    {
        "name": "Modern Wave Ankara Bundle",
        "category": "Ankara Fabrics",
        "description": "A contemporary take on wax print with a flowing, wave-like layout, six yards of cotton suited to structured modern silhouettes as much as traditional cuts.",
        "price": 30.00, "stock_quantity": 20,
        "images": ["ankara-modern-01-a.png", "ankara-modern-01-b.png"],
    },
    {
        "name": "Contour Line Wax Print",
        "category": "Ankara Fabrics",
        "description": "Clean, linear patterning on a six-yard wax print bundle, a good match for anyone wanting the authenticity of Ankara with a more minimal, modern print style.",
        "price": 28.50, "stock_quantity": 18,
        "images": ["ankara-modern-02-a.png", "ankara-modern-02-b.png"],
    },
    {
        "name": "Urban Pulse Ankara Roll",
        "category": "Ankara Fabrics",
        "description": "A high-energy modern print on premium cotton wax fabric, six yards, designed for pieces meant to stand out in a crowd.",
        "price": 31.25, "stock_quantity": 16,
        "images": ["ankara-modern-03-a.png", "ankara-modern-03-b.png"],
    },
    {
        "name": "Minimalist Grid Wax Print",
        "category": "Ankara Fabrics",
        "description": "A restrained, grid-based print for anyone who wants Ankara's texture and heritage without a busy pattern. Six yards, single main shot for this one.",
        "price": 26.00, "stock_quantity": 24,
        "images": ["ankara-modern-04.png"],
    },
    {
        "name": "Abstract Bloom Ankara",
        "category": "Ankara Fabrics",
        "description": "An abstract floral wax print bundle, six yards of cotton with a soft drape, well suited to both tailored and loose-fit garments.",
        "price": 27.00, "stock_quantity": 20,
        "images": ["ankara-modern-05.png"],
    },
    {
        "name": "Metro Ankara Bundle",
        "category": "Ankara Fabrics",
        "description": "A modern city-inspired print on six yards of quality wax cotton, part of our contemporary Ankara line for buyers who want a fresher take on a classic fabric.",
        "price": 29.99, "stock_quantity": 19,
        "images": ["ankara-modern-06-a.png", "ankara-modern-06-b.png"],
    },
    {
        "name": "Asoebi Celebration Bundle",
        "category": "Ankara Fabrics",
        "description": "Sold in bulk-friendly six-yard cuts specifically for group aso-ebi orders, so everyone at the celebration matches. Order multiples from the same batch to guarantee colour consistency across a whole party.",
        "price": 36.00, "stock_quantity": 30, "is_featured": True,
        "images": ["asoebi-01-a.png", "asoebi-01-b.png"],
    },
    {
        "name": "Heritage Lace Fabric",
        "category": "Ankara Fabrics",
        "description": "A premium lace fabric bundle available in five colourways. Six yards per order, a popular choice for occasion wear where a lighter, more textured fabric than wax print is wanted.",
        "price": 38.00, "stock_quantity": 15, "is_featured": True,
        "images": [
            "fabric-lace-white-0001-a.png", "fabric-lace-blue-0001-b.png",
            "fabric-lace-pink-0001-c.png", "fabric-lace-green-0001-d.png",
            "fabric-lace-purple-0001-e.png",
        ],
        "variants": [
            {"type": "colour", "value": "White", "stock_quantity": 8},
            {"type": "colour", "value": "Blue", "stock_quantity": 6},
            {"type": "colour", "value": "Pink", "stock_quantity": 5},
            {"type": "colour", "value": "Green", "stock_quantity": 7},
            {"type": "colour", "value": "Purple", "stock_quantity": 4},
        ],
    },
    {
        "name": "Ijebu Wax Print Bundle",
        "category": "Ankara Fabrics",
        "description": "Named for the Ijebu tradition of fine wax print craftsmanship, this six-yard bundle is one of our most authentic pieces, printed using techniques passed down through generations of local artisans.",
        "price": 33.50, "stock_quantity": 20, "is_featured": True,
        "images": ["ijebu-wax-print-010.a.png", "ijebu-wax-print-010.b.png"],
    },
    {
        "name": "New Arrival Wax Print Bundle",
        "category": "Ankara Fabrics",
        "description": "One of our newest wax print arrivals, six yards of fresh stock just brought into the catalogue. Get it before this run sells out and the next design takes its place.",
        "price": 30.50, "stock_quantity": 28,
        "images": ["newest-wax-print-050-a.png", "newest-wax-print-050-b.png"],
    },
    {
        "name": "Ile-Ife Lace Bundle",
        "category": "Ankara Fabrics",
        "description": "A premium lace-style fabric bundle from our regional collection, named for the historic city of Ile-Ife. Six yards, suited to occasion wear where a finer texture than wax print cotton is preferred.",
        "price": 35.00, "stock_quantity": 14,
        "images": ["african-wax-fabric-lace-print-luxury-000091.png"],
    },
    {
        "name": "Oyo Heritage Lace",
        "category": "Ankara Fabrics",
        "description": "Part of our city-named lace collection, six yards of premium fabric honouring the historic Oyo region, well suited to formal and celebration wear.",
        "price": 34.50, "stock_quantity": 15,
        "images": ["african-wax-fabric-lace-print-luxury-000092.png"],
    },
    {
        "name": "Ondo Luxury Lace",
        "category": "Ankara Fabrics",
        "description": "Six yards of premium lace-style fabric from our regional collection, named for Ondo. A finer weight than our standard wax prints, popular for special occasions.",
        "price": 33.00, "stock_quantity": 16,
        "images": ["african-wax-fabric-lace-print-luxury-000093.png"],
    },
    {
        "name": "Ekiti Royal Lace",
        "category": "Ankara Fabrics",
        "description": "Named for the Ekiti region, this six-yard lace bundle is one of our higher-end fabric offerings, chosen often for weddings and formal celebrations.",
        "price": 36.50, "stock_quantity": 12,
        "images": ["african-wax-fabric-lace-print-luxury-000094.png"],
    },
    {
        "name": "Osun Golden Lace",
        "category": "Ankara Fabrics",
        "description": "Six yards of premium lace fabric from our city-named collection, honouring the Osun region. A lighter weight fabric, well suited to warm-climate occasion wear.",
        "price": 34.00, "stock_quantity": 15,
        "images": ["african-wax-fabric-lace-print-luxury-000095.png"],
    },
    {
        "name": "Ogun Classic Lace",
        "category": "Ankara Fabrics",
        "description": "A six-yard lace bundle named for the Ogun region, part of our premium fabric range for buyers wanting something beyond standard wax print cotton.",
        "price": 32.50, "stock_quantity": 17,
        "images": ["african-wax-fabric-lace-print-luxury-000096.png"],
    },
    {
        "name": "Kwara Elegant Lace",
        "category": "Ankara Fabrics",
        "description": "Six yards of fine lace-style fabric named for the Kwara region, a popular choice for aso-ebi groups wanting a step up from standard cotton wax print.",
        "price": 35.50, "stock_quantity": 13,
        "images": ["african-wax-fabric-lace-print-luxury-000097.png"],
    },
    {
        "name": "Lagos Premium Lace",
        "category": "Ankara Fabrics",
        "description": "The flagship of our city-named lace collection, six yards of our finest available lace fabric, named for Lagos, the commercial heart of the trade this whole catalogue is built on.",
        "price": 37.00, "stock_quantity": 12,
        "images": ["african-wax-fabric-lace-print-luxury-000098.png"],
    },
    {
        "name": "Kano Wax Print Bundle",
        "category": "Ankara Fabrics",
        "description": "Six yards of quality cotton wax print, part of our city-named collection honouring Kano's long trading history in West African textiles.",
        "price": 26.50, "stock_quantity": 22,
        "images": ["ankara-fabric-luxury-61.png"],
    },
    {
        "name": "Kaduna Wax Print Bundle",
        "category": "Ankara Fabrics",
        "description": "A six-yard wax print bundle named for Kaduna, standard cotton weight, suited to everyday tailoring and casual traditional wear alike.",
        "price": 27.00, "stock_quantity": 20,
        "images": ["ankara-fabric-luxury-62.png"],
    },
    {
        "name": "Enugu Wax Print Bundle",
        "category": "Ankara Fabrics",
        "description": "Six yards of cotton wax print named for Enugu, a reliable, everyday fabric choice for buyers building out a basic wardrobe of traditional pieces.",
        "price": 25.75, "stock_quantity": 24,
        "images": ["ankara-fabric-luxury-63.png"],
    },
    {
        "name": "Aba Market Wax Print",
        "category": "Ankara Fabrics",
        "description": "Named for the market city of Aba, this six-yard cotton wax print bundle is one of our better-value everyday fabric options.",
        "price": 24.99, "stock_quantity": 26,
        "images": ["ankara-fabric-luxury-64.png"],
    },
    {
        "name": "Benin City Wax Print",
        "category": "Ankara Fabrics",
        "description": "Six yards of cotton wax print fabric honouring the historic Benin City, standard weight, suited to a wide range of tailoring projects.",
        "price": 28.00, "stock_quantity": 19,
        "images": ["ankara-fabric-luxury-66.png"],
    },
    {
        "name": "Calabar Coastal Wax Print",
        "category": "Ankara Fabrics",
        "description": "A six-yard wax print bundle named for the coastal city of Calabar, part of our regional cotton fabric range.",
        "price": 27.50, "stock_quantity": 21,
        "images": ["ankara-fabric-luxury-67.png"],
    },
    {
        "name": "Abuja Capital Wax Print",
        "category": "Ankara Fabrics",
        "description": "Named for the federal capital, six yards of quality cotton wax print for everyday and semi-formal traditional wear.",
        "price": 29.00, "stock_quantity": 18,
        "images": ["ankara-fabric-luxury-68.png"],
    },
    {
        "name": "Jos Plateau Wax Print",
        "category": "Ankara Fabrics",
        "description": "Six yards of cotton wax print fabric named for the Jos Plateau region, a dependable, everyday-priced piece in our regional collection.",
        "price": 26.25, "stock_quantity": 23,
        "images": ["ankara-fabric-luxury-69.png"],
    },
    {
        "name": "Ibadan Wax Print Bundle",
        "category": "Ankara Fabrics",
        "description": "Named for Ibadan, one of West Africa's largest cities, this six-yard cotton wax print bundle is a solid, versatile everyday choice.",
        "price": 25.50, "stock_quantity": 25,
        "images": ["ankara-fabric-luxury-70.png"],
    },
    {
        "name": "Sokoto Heritage Wax Print",
        "category": "Ankara Fabrics",
        "description": "Six yards of wax print cotton honouring the historic Sokoto region, part of our full regional fabric line.",
        "price": 28.75, "stock_quantity": 17,
        "images": ["ankara-fabric-luxury-71.png"],
    },
    {
        "name": "Warri Delta Wax Print",
        "category": "Ankara Fabrics",
        "description": "Named for the Niger Delta city of Warri, this six-yard cotton wax print bundle rounds out our regional collection with a reliable, everyday fabric option.",
        "price": 27.25, "stock_quantity": 20,
        "images": ["ankara-fabric-luxury-72.png"],
    },
    {
        "name": "Owerri Wax Print Bundle",
        "category": "Ankara Fabrics",
        "description": "Six yards of standard-weight cotton wax print named for Owerri, suited to casual and semi-formal traditional wear alike.",
        "price": 26.75, "stock_quantity": 21,
        "images": ["ankara-fabric-luxury-73.png"],
    },
    {
        "name": "Uyo Coastal Wax Print",
        "category": "Ankara Fabrics",
        "description": "Named for the coastal city of Uyo, six yards of quality cotton wax print, part of our full regional fabric range.",
        "price": 25.99, "stock_quantity": 22,
        "images": ["ankara-fabric-luxury-74.png"],
    },
    {
        "name": "Akure Sunrise Wax Print",
        "category": "Ankara Fabrics",
        "description": "The final piece in our regional wax print series, six yards of cotton fabric named for Akure, closing out one of our most complete fabric collections.",
        "price": 29.50, "stock_quantity": 19,
        "images": ["ankara-fabric-luxury-75.png"],
    },
]

REVIEWER_USERNAMES = [
    "amaka_t", "kwame_o", "ngozi_b", "tunde_f", "aisha_r", "chidi_m", "folake_s", "ebuka_n",
]

# Grouped by rating so a 5-star review never accidentally reads lukewarm.
REVIEW_POOL = {
    5: [
        ("Exactly as described", "This is exactly what I expected, great quality and arrived well packaged."),
        ("Really happy with this", "Bought this as a gift and ended up keeping it for myself instead."),
        ("Will buy again", "Second time ordering this one. Consistent quality every time."),
    ],
    4: [
        ("Good quality", "Solid product, does exactly what it says. Minor delay in delivery but worth the wait."),
        ("Would recommend", "Good value for the price. Colour is slightly different in person but still nice."),
    ],
    3: [
        ("It's okay", "Does the job but nothing special. Packaging could be better."),
        ("Decent for the price", "Fair quality for what I paid. Might try a different variant next time."),
    ],
}