# Generated by Django 6.1.1 on 2026-09-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_sku"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="units_sold",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
