# Generated by Django 6.1.1 on 2026-09-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_units_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="show_in_main_nav",
            field=models.BooleanField(
                default=True,
                help_text="Checked: shows directly in the main nav. Unchecked: only appears in the Special Offers dropdown.",
            ),
        ),
    ]
